// Generated by `opennextjs-cloudflare build` before Wrangler bundles this entrypoint.
// @ts-ignore The generated module is intentionally absent in a clean checkout.
import openNextWorker from "./.open-next/worker.js";

type WorkerEnv = Record<string, unknown> & { CRON_SECRET?: string };
type WorkerContext = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: openNextWorker.fetch,
  async scheduled(controller: { cron: string }, env: WorkerEnv, ctx: WorkerContext) {
    const path = controller.cron === "30 3 * * *" ? "aiosell-mappings"
      : controller.cron === "30 4,6,8,10,12,14,16 * * *" ? "reconciliation-reminder" : null;
    if (!path) return;
    if (!env.CRON_SECRET) {
      throw new Error("Scheduled job failed: CRON_SECRET is not configured");
    }
    const request = new Request(`https://goko.internal/api/cron/${path}`, {
      method: "POST",
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response = await openNextWorker.fetch(request, env, ctx);
    if (!response.ok) {
      throw new Error(`Scheduled job ${path} failed: HTTP ${response.status}`);
    }
  },
};
