"use client";

import { useCallback, useEffect, useState } from "react";
import { PencilIcon, XIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { DEFAULT_EXPENSE_CATEGORIES } from "@/lib/accountCategories";

const today = () => new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" });
const empty = () => ({ id: "", name: "", amount: "", category: "", customCategory: "", subCategory: "", purpose: "", frequency: "monthly", startDate: today(), endDate: "", postingMode: "review", mainCategory: "stay_expense", paymentMethod: "cash", vendorId: "", accountId: "" });
const label = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, char => char.toUpperCase());
const toFiles = (files: File[]) => Promise.all(files.map(file => new Promise<any>(resolve => { const reader = new FileReader(); reader.onload = () => resolve({ data: (reader.result as string).split(",")[1], mime: file.type, name: file.name }); reader.readAsDataURL(file); })));

function RuleFields({ form, set, categories, vendors, accounts }: { form: any; set: (key: string, value: string) => void; categories: string[]; vendors: any[]; accounts: any[] }) {
  return <div className="grid gap-3 sm:grid-cols-2">
    <div><Label>Name *</Label><Input required value={form.name} onChange={e => set("name", e.target.value)} /></div><div><Label>Fixed amount (₹)</Label><Input type="number" min="0" step="0.01" value={form.amount} onChange={e => set("amount", e.target.value)} placeholder="Optional" /></div>
    <div><Label>Category *</Label><select required value={form.category} onChange={e => set("category", e.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Select category</option>{categories.map(category => <option key={category} value={category}>{category}</option>)}</select></div><div><Label>Sub-category</Label><Input value={form.subCategory || ""} onChange={e => set("subCategory", e.target.value)} /></div>
    {form.category === "Others" && <div><Label>Custom category *</Label><Input required value={form.customCategory || ""} onChange={e => set("customCategory", e.target.value)} /></div>}<div><Label>Notes</Label><Input value={form.purpose} onChange={e => set("purpose", e.target.value)} /></div>
    <div><Label>Frequency</Label><select value={form.frequency} onChange={e => set("frequency", e.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></div><div><Label>Type</Label><select value={form.mainCategory} onChange={e => set("mainCategory", e.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="stay_expense">Stay Expense</option><option value="food_expense">Food Expense</option><option value="goko_expense">Goko Expense</option></select></div>
    <div><Label>Start date</Label><Input required type="date" min={today()} value={form.startDate} onChange={e => set("startDate", e.target.value)} /></div><div><Label>End date (optional)</Label><Input type="date" min={form.startDate} value={form.endDate || ""} onChange={e => set("endDate", e.target.value)} /></div>
    <div><Label>Posting</Label><select value={form.postingMode} onChange={e => set("postingMode", e.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="review">Create draft for review</option><option value="automatic" disabled={!form.amount}>Post automatically</option></select></div><div><Label>Vendor</Label><select value={form.vendorId} onChange={e => set("vendorId", e.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">No vendor</option>{vendors.map(vendor => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</select></div>
    <div><Label>Payment method</Label><select value={form.paymentMethod} onChange={e => { set("paymentMethod", e.target.value); set("accountId", ""); }} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="cash">Cash</option><option value="online">Online</option></select></div>{form.paymentMethod === "online" && <div><Label>Bank account *</Label><select required value={form.accountId} onChange={e => set("accountId", e.target.value)} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Select account</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.nickname || account.name}</option>)}</select></div>}
  </div>;
}

export function AdminRecurringExpenses({ password, username }: { password: string; username?: string }) {
  const [form, setForm] = useState<any>(empty), [editing, setEditing] = useState<any | null>(null), [rules, setRules] = useState<any[]>([]), [items, setItems] = useState<any[]>([]), [vendors, setVendors] = useState<any[]>([]), [accounts, setAccounts] = useState<any[]>([]), [categories, setCategories] = useState(DEFAULT_EXPENSE_CATEGORIES), [files, setFiles] = useState<File[]>([]), [error, setError] = useState("");
  const api = useCallback((url: string, body: any) => fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password, username, ...body }) }), [password, username]);
  const load = useCallback(async () => { const [schedule, options, categoryOptions] = await Promise.all([api("/api/admin/recurring-expenses", { action: "list" }), api("/api/admin/expenses", { action: "getExpenseEditOptions" }), api("/api/admin/expenses", { action: "getExpenseCategories" })]); if (schedule.ok) { const data = await schedule.json(); setRules(data.rules || []); setItems((data.occurrences || []).map((row: any) => row.occurrence)); } if (options.ok) { const data = await options.json(); setVendors(data.vendors || []); setAccounts(data.accounts || []); } if (categoryOptions.ok) setCategories((await categoryOptions.json()).categories || DEFAULT_EXPENSE_CATEGORIES); }, [api]);
  useEffect(() => { void load(); }, [load]);
  const set = (key: string, value: string) => setForm((old: any) => ({ ...old, [key]: value }));
  const setEdit = (key: string, value: string) => setEditing((old: any) => ({ ...old, [key]: value }));
  const payload = (value: any) => ({ action: "saveRule", ...value, amount: value.amount === "" ? null : Math.round(Number(value.amount) * 100) });
  async function save(event: React.FormEvent, value = form) { event.preventDefault(); setError(""); const response = await api("/api/admin/recurring-expenses", payload(value)); if (!response.ok) return setError((await response.json()).error || "Could not save rule"); if (value.id) setEditing(null); else setForm(empty()); await load(); }
  async function post(item: any) { const raw = prompt(`Amount for ${item.category} (₹)`, item.amount ? String(item.amount / 100) : ""); if (raw == null) return; const amount = Math.round(Number(raw) * 100); if (!Number.isSafeInteger(amount) || amount <= 0) return setError("Enter a valid amount"); const response = await api("/api/admin/expenses", { action: "addExpense", idempotencyKey: crypto.randomUUID(), amount, category: item.category, customCategory: item.customCategory, purpose: item.purpose, vendorId: item.vendorId, accountId: item.accountId, paymentMethod: item.paymentMethod, mainCategory: item.mainCategory, subCategory: item.subCategory, expenseDate: item.dueDate, billFiles: await toFiles(files) }); if (!response.ok) return setError((await response.json()).error || "Could not post expense"); const expense = await response.json(); const linked = await api("/api/admin/recurring-expenses", { action: "linkExpense", id: item.id, expenseId: expense.id }); if (!linked.ok) return setError("Expense saved but could not link to its recurring draft; retry Post expense."); setFiles([]); await load(); }
  const edit = (rule: any) => { setError(""); setEditing({ ...rule, amount: rule.amount == null ? "" : String(rule.amount / 100), vendorId: rule.vendorId ? String(rule.vendorId) : "", accountId: rule.accountId ? String(rule.accountId) : "", endDate: rule.endDate || "" }); };
  const accountName = (id: any) => accounts.find(account => String(account.id) === String(id))?.nickname || accounts.find(account => String(account.id) === String(id))?.name || "Account";
  const pending = items.filter(item => item.status === "pending");
  return <div className="space-y-6"><form onSubmit={save} className="rounded-2xl border border-brand-mist bg-white p-5"><h3 className="font-display text-lg font-bold text-brand-green-dark">Create recurring expense</h3><p className="mt-1 text-sm text-brand-green-dark/60">Review rules create drafts; automatic rules require a fixed amount.</p><div className="mt-4"><RuleFields form={form} set={set} categories={categories} vendors={vendors} accounts={accounts} /></div>{error && !editing && <p className="mt-3 text-sm text-red-600">{error}</p>}<Button className="mt-4" type="submit">Save recurring expense</Button></form>
    <section className="rounded-2xl border border-brand-mist bg-white p-5"><h3 className="font-display text-lg font-bold text-brand-green-dark">Due and overdue</h3>{pending.length === 0 ? <p className="mt-3 text-sm text-brand-green-dark/60">No recurring expenses are due.</p> : <><Label className="mt-3 block">Bill files for the selected draft</Label><Input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e => setFiles(Array.from(e.target.files || []).slice(0, 5))} />{pending.map(item => <div key={item.id} className="mt-2 flex flex-wrap justify-between gap-2 rounded border p-2"><span>{item.dueDate} · {item.category}{item.amount ? ` · ₹${(item.amount / 100).toFixed(2)}` : " · Amount needed"}{item.error ? ` · ${item.error}` : ""}</span><span className="flex gap-2"><Button size="sm" onClick={() => void post(item)}>Post expense</Button><Button size="sm" variant="outline" onClick={() => void api("/api/admin/recurring-expenses", { action: "skip", id: item.id }).then(load)}>Skip</Button></span></div>)}</>}</section>
    <section className="rounded-2xl border border-brand-mist bg-white p-5"><h3 className="font-display text-lg font-bold text-brand-green-dark">Rules</h3>{rules.length === 0 ? <p className="mt-3 text-sm text-brand-green-dark/60">No recurring expense rules yet.</p> : <div className="mt-3 space-y-3">{rules.map(rule => <article key={rule.id} className="rounded-xl border border-brand-mist bg-brand-sand/20 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2 text-xs font-semibold"><span className={rule.active ? "rounded bg-emerald-50 px-2 py-1 text-emerald-700" : "rounded bg-slate-100 px-2 py-1 text-slate-600"}>{rule.active ? "Active" : "Disabled"}</span><span className="rounded bg-brand-green/10 px-2 py-1 text-brand-green">{label(rule.frequency)}</span><span className="rounded bg-brand-sand px-2 py-1 text-brand-green-dark">{rule.postingMode === "automatic" ? "Auto-post" : "Review"}</span></div><h4 className="mt-2 font-display text-base font-bold text-brand-green-dark">{rule.name}</h4></div><button type="button" aria-label={`Edit ${rule.name}`} onClick={() => edit(rule)} className="rounded-md p-2 text-brand-green-dark/70 hover:bg-brand-green/10"><PencilIcon className="h-4 w-4" /></button></div><div className="mt-3 grid gap-x-5 gap-y-2 text-xs text-brand-green-dark/75 sm:grid-cols-2 lg:grid-cols-3"><span><strong>Amount:</strong> {rule.amount == null ? "Set when posted" : `₹${(rule.amount / 100).toFixed(2)}`}</span><span><strong>Type:</strong> {label(rule.mainCategory)}</span><span><strong>Category:</strong> {rule.category}{rule.subCategory ? ` · ${rule.subCategory}` : ""}</span><span><strong>Schedule:</strong> {label(rule.frequency)} · {rule.startDate} → {rule.endDate || "No end date"}</span><span><strong>Payment:</strong> {label(rule.paymentMethod)}{rule.paymentMethod === "online" ? ` · ${accountName(rule.accountId)}` : ""}</span><span><strong>Vendor:</strong> {vendors.find(vendor => String(vendor.id) === String(rule.vendorId))?.name || "No vendor"}</span>{rule.purpose && <span className="sm:col-span-2 lg:col-span-3"><strong>Notes:</strong> {rule.purpose}</span>}<span className="sm:col-span-2 lg:col-span-3 text-brand-green-dark/50">Created by {rule.createdBy || "Admin"}{rule.updatedAt ? ` · Updated ${new Date(rule.updatedAt).toLocaleString("en-IN")}` : ""}</span></div><div className="mt-3"><Button size="sm" variant="outline" onClick={() => void api("/api/admin/recurring-expenses", { action: "setActive", id: rule.id, active: !rule.active }).then(load)}>{rule.active ? "Disable" : "Enable"}</Button></div></article>)}</div>}</section>
    {editing && <div className="fixed inset-0 z-[60] flex items-start justify-center overflow-y-auto overscroll-contain bg-black/40 p-4 sm:items-center" onClick={() => setEditing(null)}><form onSubmit={event => save(event, editing)} className="max-h-[min(90dvh,100%)] w-full max-w-2xl overflow-y-auto overscroll-contain rounded-2xl bg-white p-5 shadow-xl dark:bg-card" onClick={event => event.stopPropagation()}><div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold text-brand-green-dark">Edit recurring expense</h3><button type="button" aria-label="Close recurring expense editor" onClick={() => setEditing(null)}><XIcon className="h-5 w-5" /></button></div><div className="mt-4"><RuleFields form={editing} set={setEdit} categories={categories} vendors={vendors} accounts={accounts} /></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex gap-2"><Button type="submit">Save changes</Button><Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancel</Button></div></form></div>}
  </div>;
}
