import { expect, test } from "@playwright/test";
test("admin can create, edit, disable, and skip recurring expenses", async ({ page }) => {
  const calls: any[] = [];
  await page.route("**/api/**", async route => { const url = new URL(route.request().url()), body = JSON.parse(route.request().postData() || "{}"); if (url.pathname === "/api/auth/login") return route.fulfill({ json: { role: "admin", username: "e2e", permissions: {} } }); if (url.pathname === "/api/auth/session") return route.fulfill({ status: 401, json: {} }); if (url.pathname === "/api/admin/recurring-expenses") { calls.push(body); return route.fulfill({ json: body.action === "list" ? { rules: [{ id: 7, name: "Internet", frequency: "monthly", postingMode: "review", active: 1, mainCategory: "stay_expense", category: "Utilities", paymentMethod: "cash", startDate: "2026-09-29" }], occurrences: [{ occurrence: { id: 9, status: "pending", dueDate: "2026-09-29", category: "Utilities", purpose: "Internet", paymentMethod: "cash", mainCategory: "stay_expense", subCategory: "", amount: null } }] } : { success: true } }); } if (url.pathname === "/api/admin/expenses") return route.fulfill({ json: body.action === "getExpenseEditOptions" ? { vendors: [], accounts: [] } : { id: 91 } }); return route.fulfill({ json: {} }); });
  await page.goto("/admin?section=expenditure"); await page.locator("#admin-user").fill("e2e"); await page.locator("#admin-pw").fill("pw"); await page.getByRole("button", { name: "Login" }).click(); await page.getByRole("button", { name: "Recurring Expenses" }).click(); await expect(page.getByRole("heading", { name: "Create recurring expense" })).toBeVisible();
  await page.locator("form input").nth(0).fill("Internet"); await page.locator("form select").nth(0).selectOption("Utilities"); await page.getByRole("button", { name: "Save recurring expense" }).click(); await expect.poll(() => calls.some(x => x.action === "saveRule" && x.name === "Internet")).toBe(true);
  await page.getByLabel("Edit Internet").click(); const editForm = page.getByRole("heading", { name: "Edit recurring expense" }).locator("xpath=ancestor::form"); await expect(editForm).toBeVisible(); await editForm.locator("input").first().fill("Internet & Utilities"); await page.getByRole("button", { name: "Save changes" }).click(); await expect.poll(() => calls.some(x => x.action === "saveRule" && x.id === 7)).toBe(true);
  await page.getByRole("button", { name: "Disable" }).click(); await page.getByRole("button", { name: "Skip" }).click(); await expect.poll(() => calls.some(x => x.action === "setActive") && calls.some(x => x.action === "skip")).toBe(true);
});
